<a href="https://colab.research.google.com/github/khush3012/Python-Lab/blob/main/Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 12 - Data Wrangling
## Name : Khush Chauhan
##PRN: 25070123062
##Batch: Entc - A3
## Date : 18/03/2026

In [48]:
import pandas as  pd
import numpy as np
df1 = pd.DataFrame({'C1': [11,21,np.nan], 'C2':[15,np.nan,np.nan], 'C3':[10,20,30]})

df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [49]:
df1.isna() # Boolean function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [50]:
df1.isna().sum() #columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [51]:
df1.dropna() #NaN Rows are dropped

     C1    C2  C3
0  11.0  15.0  10

In [52]:
df1.fillna(value = 'DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [53]:
df1.fillna(df1.mean()) # Mean values of columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [54]:
# Preprocessing on a Dataset - 1
import pandas as pd

data = {
    "Roll no":[101,102,103,104,105],
    "Name" : ["Clark","Lana","Lex","Sydney","Lois"],
    "Age" : [20, "-", 21, 20, "22"],
    "Marks" : [85,90, "-", 88,76],
    "Department" : ["Aero","IT","Automobile","ECE","CSE"],
    "Admission Date" : ["01-06-2023", "03-06-2023","05-06-2023","07-06-2023","12-06-2023"]
}

df = pd.DataFrame(data)
df.to_csv("student_data.csv", index=False)

In [55]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
df = pd.read_csv("student_data.csv")

print("Original Data: ")
print(df)

Original Data:
   Roll no    Name Age Marks  Department Admission Date
0      101   Clark  20    85        Aero     01-06-2023
1      102    Lana   -    90          IT     03-06-2023
2      103     Lex  21     -  Automobile     05-06-2023
3      104  Sydney  20    88         ECE     07-06-2023
4      105    Lois  22    76         CSE     12-06-2023

In [56]:
# Step 2: Replace '-' with NaN to mark missing vlaues

df.replace("-", np.nan, inplace=True)

#Convert columns to numeric where needed

df["Age"] = pd.to_numeric(df["Age"], errors = 'coerce')
df["Marks"] = pd.to_numeric(df["Marks"], errors = 'coerce')

# When converting data (like strings to datetime) if some values are invalid or cannot be converted, instead of throwing an error, it will: Replace thoe invald values with NaT (Not a Time)

df

   Roll no    Name   Age  Marks  Department Admission Date
0      101   Clark  20.0   85.0        Aero     01-06-2023
1      102    Lana   NaN   90.0          IT     03-06-2023
2      103     Lex  21.0    NaN  Automobile     05-06-2023
3      104  Sydney  20.0   88.0         ECE     07-06-2023
4      105    Lois  22.0   76.0         CSE     12-06-2023

In [57]:
# Step 3: Check missing values

print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Roll no           0
Name              0
Age               1
Marks             1
Department        0
Admission Date    0
dtype: int64

In [58]:
# Fill missing Age with mean

df["Age"].fillna(df["Age"].mean(), inplace=True)

/tmp/ipykernel_790/2973084696.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)

In [59]:
print(df.isnull().sum())

Roll no           0
Name              0
Age               0
Marks             1
Department        0
Admission Date    0
dtype: int64

In [60]:
# Step 5: Fix inconsistent text formatting

df["Department"] = df["Department"].str.upper()
df

   Roll no    Name    Age  Marks  Department Admission Date
0      101   Clark  20.00   85.0        AERO     01-06-2023
1      102    Lana  20.75   90.0          IT     03-06-2023
2      103     Lex  21.00    NaN  AUTOMOBILE     05-06-2023
3      104  Sydney  20.00   88.0         ECE     07-06-2023
4      105    Lois  22.00   76.0         CSE     12-06-2023

In [61]:
# Step 6: Convert admission_date to standard datetime format

df["Admission Date"] = pd.to_datetime(df["Admission Date"], errors = 'coerce')
df

   Roll no    Name    Age  Marks  Department Admission Date
0      101   Clark  20.00   85.0        AERO     2023-01-06
1      102    Lana  20.75   90.0          IT     2023-03-06
2      103     Lex  21.00    NaN  AUTOMOBILE     2023-05-06
3      104  Sydney  20.00   88.0         ECE     2023-07-06
4      105    Lois  22.00   76.0         CSE     2023-12-06

In [62]:
# Step 7: Show cleaned data

print("Cleaned Data:")
print(df)

Cleaned Data:
   Roll no    Name    Age  Marks  Department Admission Date
0      101   Clark  20.00   85.0        AERO     2023-01-06
1      102    Lana  20.75   90.0          IT     2023-03-06
2      103     Lex  21.00    NaN  AUTOMOBILE     2023-05-06
3      104  Sydney  20.00   88.0         ECE     2023-07-06
4      105    Lois  22.00   76.0         CSE     2023-12-06

In [64]:
# Step 8: Save cleaned dataset

df.to_csv("cleaned_student_data.csv", index = False)
print("\n Cleaned CSV file saved as cleaned_student_data.csv")

 Cleaned CSV file saved as cleaned_student_data.csv

In [65]:
# Working with missing values on Dataset -2

df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [66]:
df.isna().sum() # Attritbutes are displayed

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [77]:
# Imputing missing values

#1. Luggage Room
df['Luggage.room'] = df['Luggage.room'].fillna(value=df['Luggage.room'].mean())

In [76]:
#2. Rear seat room
df['Rear.seat.room'] = df['Rear.seat.room'].fillna(value=df['Rear.seat.room'].mean())

In [75]:
#3. Airbags
df['AirBags'] = df['AirBags'].fillna(value=df['AirBags'].mode().values[0])

In [79]:
# Save cleaned dataset
df.to_csv("cleaned_Cars93.csv", index= False)