<a href="https://colab.research.google.com/github/khush3012/Python-Lab/blob/main/Data_Normalization_and_Data_Type_Conversion_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 14 - Data Normalization and Data Type Conversion
##Name : Khush Chauhan
## PRN : 25070123062
## Batch : A3
## Date : 1st April 2026

# Part A - Data Normalization

In [3]:
# Dataset
import pandas as pd
import numpy as no

data = {
    'Product' : ['Laptop','Mobile','iPad','Headphones','Smartwatch','Camera'],
    'Price' : [120000, 65000, 83000, 62500, 55000, 89000],
    'Units_sold' : [25,60,35,80,50,15],
    'Discount' : [10,15,12,20,18,8]
}
df = pd.DataFrame(data)
df

      Product   Price  Units_sold  Discount
0      Laptop  120000          25        10
1      Mobile   65000          60        15
2        iPad   83000          35        12
3  Headphones   62500          80        20
4  Smartwatch   55000          50        18
5      Camera   89000          15         8

In [5]:
# 1. Min-Max Normalization
# Min-Max normalization for the price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\nMin-Max Normalizaed Price: ")
print(df[['Product','Price','Price_MinMax']])

Min-Max Normalizaed Price:
      Product   Price  Price_MinMax
0      Laptop  120000      1.000000
1      Mobile   65000      0.153846
2        iPad   83000      0.430769
3  Headphones   62500      0.115385
4  Smartwatch   55000      0.000000
5      Camera   89000      0.523077

In [7]:
df['Dis_MinMax'] = (df['Discount'] - df['Discount'].min()) / (df['Discount'].max() - df['Discount'].min())

print("\nMin-Max Normalizaed Discount: ")
print(df[['Product','Discount','Dis_MinMax']])

Min-Max Normalizaed Discount:
      Product  Discount  Dis_MinMax
0      Laptop        10    0.166667
1      Mobile        15    0.583333
2        iPad        12    0.333333
3  Headphones        20    1.000000
4  Smartwatch        18    0.833333
5      Camera         8    0.000000

In [8]:
# Normalize multiple columns

cols = ['Price','Units_sold','Discount']
df_norm = (df[cols]-df[cols].min())/(df[cols].max()-df[cols].min())
df[cols] = df_norm
df

,Product,Price,Units_sold,Discount,Price_minmax,Price_MinMax,Dis_MinMax
0,Laptop,1.000000,0.153846,0.166667,1.000000,1.000000,0.166667
1,Mobile,0.153846,0.692308,0.583333,0.153846,0.153846,0.583333
2,iPad,0.430769,0.307692,0.333333,0.430769,0.430769,0.333333
3,Headphones,0.115385,1.000000,1.000000,0.115385,0.115385,1.000000
4,Smartwatch,0.000000,0.538462,0.833333,0.000000,0.000000,0.833333
5,Camera,0.523077,0.000000,0.000000,0.523077,0.523077,0.000000

In [9]:
# 2. Z-Score Normalization

df['Units_Zscore'] = (df['Units_sold'] - df['Units_sold'].mean()) / df['Units_sold'].std()

print("\nZ-Score Normalizaed Units: ")
print(df[['Product','Units_sold','Units_Zscore']])

Z-Score Normalizaed Units:
      Product  Units_sold  Units_Zscore
0      Laptop    0.153846     -0.799885
1      Mobile    0.692308      0.660775
2        iPad    0.307692     -0.382554
3  Headphones    1.000000      1.495437
4  Smartwatch    0.538462      0.243443
5      Camera    0.000000     -1.217216

In [10]:
# 3. Decimal Scaling

df['Price_DS'] = df['Price'] / 100000

print("\nDecimal Scaling Normalizaed Price: ")
print(df[['Product','Price','Price_DS']])

Decimal Scaling Normalizaed Price:
      Product     Price  Price_DS
0      Laptop  1.000000  0.000010
1      Mobile  0.153846  0.000002
2        iPad  0.430769  0.000004
3  Headphones  0.115385  0.000001
4  Smartwatch  0.000000  0.000000
5      Camera  0.523077  0.000005

# Part B - Turning categorical variables into quantitative variables in Pyhton

In [16]:
data1 = {
    'Order_ID' : [101,102,103,104,105, 106],
    'Customer_gender' : ['Male','Female','Female','Male','Female','Male'],
    'Product_category' : ['Electronics','Clothing','Electronics','Clothing','Electronics','Clothing'],
    'Payment_method' : ['Credit Card','PayPal','PayPal','Credit Card','PayPal','Credit Card'],
    'City' : ['New York','Philadelphia','San Diego','Los Angeles','Boston', 'Chicago'],
    'Order_value' : [4500,2300,3200,5200,1800,4100]
}
df1 = pd.DataFrame(data1)
df1

,Order_ID,Customer_gender,Product_category,Payment_method,City,Order_value
0,101,Male,Electronics,Credit Card,New York,4500
1,102,Female,Clothing,PayPal,Philadelphia,2300
2,103,Female,Electronics,PayPal,San Diego,3200
3,104,Male,Clothing,Credit Card,Los Angeles,5200
4,105,Female,Electronics,PayPal,Boston,1800
5,106,Male,Clothing,Credit Card,Chicago,4100

In [18]:
# Method 1: Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['Gender_Label'] = le.fit_transform(df1['Customer_gender'])
print(df1)

   Order_ID Customer_gender Product_category Payment_method          City  \
0       101            Male      Electronics    Credit Card      New York
1       102          Female         Clothing         PayPal  Philadelphia
2       103          Female      Electronics         PayPal     San Diego
3       104            Male         Clothing    Credit Card   Los Angeles
4       105          Female      Electronics         PayPal        Boston
5       106            Male         Clothing    Credit Card       Chicago

   Order_value  Gender_Label
0         4500             1
1         2300             0
2         3200             0
3         5200             1
4         1800             0
5         4100             1

In [20]:
# Method 2: One-Hot Encoding

df_encoded = pd.get_dummies(df1, columns=['Payment_method'])
print(df_encoded)

   Order_ID Customer_gender Product_category          City  Order_value  \
0       101            Male      Electronics      New York         4500
1       102          Female         Clothing  Philadelphia         2300
2       103          Female      Electronics     San Diego         3200
3       104            Male         Clothing   Los Angeles         5200
4       105          Female      Electronics        Boston         1800
5       106            Male         Clothing       Chicago         4100

   Gender_Label  Payment_method_Credit Card  Payment_method_PayPal
0             1                        True                  False
1             0                       False                   True
2             0                       False                   True
3             1                        True                  False
4             0                       False                   True
5             1                        True                  False

In [23]:
# Method 3 : Dummy Encoding (Drop first)

df_dummy = pd.get_dummies(df1, columns=['Product_category'], drop_first=True)
print(df_dummy)

   Order_ID Customer_gender Payment_method          City  Order_value  \
0       101            Male    Credit Card      New York         4500
1       102          Female         PayPal  Philadelphia         2300
2       103          Female         PayPal     San Diego         3200
3       104            Male    Credit Card   Los Angeles         5200
4       105          Female         PayPal        Boston         1800
5       106            Male    Credit Card       Chicago         4100

   Gender_Label  Product_category_Electronics
0             1                          True
1             0                         False
2             0                          True
3             1                         False
4             0                          True
5             1                         False

# New Dataset Operations

In [24]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [31]:
# 1. Min-Max

df['Price_minmax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print("\nMin-Max Normalized Price: ")
print(df[['Product_Name','Price','Price_minmax']])

df['Rating_minmax'] = (df['Rating'] - df['Rating'].min()) / (df['Rating'].max() - df['Rating'].min())
print("\nMin-Max Normalized Rating: ")
print(df[['Product_Name','Rating','Rating_minmax']])

df['Reviews_minmax'] = (df['Reviews'] - df['Reviews'].min()) / (df['Reviews'].max() - df['Reviews'].min())
print("\nMin-Max Normalized Reviews: ")
print(df[['Product_Name','Reviews','Reviews_minmax']])

df['Units_Sold_minmax'] = (df['Units_Sold'] - df['Units_Sold'].min()) / (df['Units_Sold'].max() - df['Units_Sold'].min())
print("\nMin-Max Normalized Units Sold: ")
print(df[['Product_Name','Units_Sold','Units_Sold_minmax']])

Min-Max Normalized Price:
                   Product_Name  Price  Price_minmax
0                Wireless Mouse    799      0.020243
1             Bluetooth Speaker   1499      0.048583
2                  USB Keyboard    699      0.016194
3                Gaming Headset   2499      0.089069
4                    Smartwatch   3999      0.149798
5                    Power Bank   1199      0.036437
6                  Laptop Stand    899      0.024291
7                        Webcam   1899      0.064777
8                  Portable SSD   5499      0.210526
9              Wireless Charger    999      0.028340
10  Noise Cancelling Headphones   7999      0.311741
11          Mechanical Keyboard   4599      0.174089
12                 Gaming Mouse   1599      0.052632
13                 Tablet Stand    699      0.016194
14                      USB Hub    899      0.024291
15          External Hard Drive   6499      0.251012
16            Smartphone Tripod   1199      0.036437
17              Laptop Backpack   1999      0.068826
18            Bluetooth Earbuds   2999      0.109312
19                LED Desk Lamp   1299      0.040486
20                 Phone Holder    499      0.008097
21            Wireless Keyboard   2499      0.089069
22             Portable Monitor   8999      0.352227
23                   Smart Plug    799      0.020243
24                  WiFi Router   3499      0.129555
25              Graphics Tablet   4599      0.174089
26                   VR Headset  12999      0.514170
27                   Microphone   2199      0.076923
28             Smart Light Bulb    699      0.016194
29           Laptop Cooling Pad   1499      0.048583
30                Action Camera   9999      0.392713
31               Smart Doorbell   5999      0.230769
32              Streaming Stick   3499      0.129555
33           Portable Projector  11999      0.473684
34                 Gaming Chair  15999      0.635628
35               Desk Organizer    599      0.012146
36              USB Flash Drive    799      0.020243
37       Phone Screen Protector    299      0.000000
38                Laptop Sleeve    999      0.028340
39           Wireless Presenter   1499      0.048583
40         Tablet Keyboard Case   2999      0.109312
41             Smart Thermostat  10999      0.433198
42              Security Camera   4999      0.190283
43                 Drone Camera  24999      1.000000
44              Electric Kettle   1999      0.068826
45                    Air Fryer   7999      0.311741
46                 Robot Vacuum  18999      0.757085
47                  Smart Scale   2499      0.089069
48          Digital Photo Frame   3499      0.129555
49                 Portable Fan    999      0.028340

Min-Max Normalized Rating:
                   Product_Name  Rating  Rating_minmax
0                Wireless Mouse     4.3       0.428571
1             Bluetooth Speaker     4.5       0.714286
2                  USB Keyboard     4.1       0.142857
3                Gaming Headset     4.6       0.857143
4                    Smartwatch     4.4       0.571429
5                    Power Bank     4.2       0.285714
6                  Laptop Stand     4.0       0.000000
7                        Webcam     4.3       0.428571
8                  Portable SSD     4.7       1.000000
9              Wireless Charger     4.2       0.285714
10  Noise Cancelling Headphones     4.6       0.857143
11          Mechanical Keyboard     4.5       0.714286
12                 Gaming Mouse     4.4       0.571429
13                 Tablet Stand     4.1       0.142857
14                      USB Hub     4.2       0.285714
15          External Hard Drive     4.6       0.857143
16            Smartphone Tripod     4.3       0.428571
17              Laptop Backpack     4.4       0.571429
18            Bluetooth Earbuds     4.5       0.714286
19                LED Desk Lamp     4.3       0.428571
20                 Phone Holder     4.0       0.000000
21            Wireless Keyboard     4.4       0.571429
22             Portable Monitor     4.6       0.857143
23                   Smart Plug     4.2       0.285714
24                  WiFi Router     4.5       0.714286
25              Graphics Tablet     4.4       0.571429
26                   VR Headset     4.7       1.000000
27                   Microphone     4.3       0.428571
28             Smart Light Bulb     4.2       0.285714
29           Laptop Cooling Pad     4.3       0.428571
30                Action Camera     4.6       0.857143
31               Smart Doorbell     4.5       0.714286
32              Streaming Stick     4.4       0.571429
33           Portable Projector     4.6       0.857143
34                 Gaming Chair     4.7       1.000000
35               Desk Organizer     4.1       0.142857
36              USB Flash Drive     4.2       0.285714
37       Phone Screen Protector     4.0       0.000000
38                Laptop Sleeve     4.3       0.428571
39           Wireless Presenter     4.4       0.571429
40         Tablet Keyboard Case     4.5       0.714286
41             Smart Thermostat     4.6       0.857143
42              Security Camera     4.4       0.571429
43                 Drone Camera     4.7       1.000000
44              Electric Kettle     4.3       0.428571
45                    Air Fryer     4.6       0.857143
46                 Robot Vacuum     4.5       0.714286
47                  Smart Scale     4.4       0.571429
48          Digital Photo Frame     4.3       0.428571
49                 Portable Fan     4.2       0.285714

Min-Max Normalized Reviews:
                   Product_Name  Reviews  Reviews_minmax
0                Wireless Mouse     1520        0.291005
1             Bluetooth Speaker      980        0.148148
2                  USB Keyboard      870        0.119048
3                Gaming Headset     2100        0.444444
4                    Smartwatch     3050        0.695767
5                    Power Bank     1750        0.351852
6                  Laptop Stand      620        0.052910
7                        Webcam     1120        0.185185
8                  Portable SSD     1850        0.378307
9              Wireless Charger      760        0.089947
10  Noise Cancelling Headphones     4200        1.000000
11          Mechanical Keyboard     2100        0.444444
12                 Gaming Mouse     1300        0.232804
13                 Tablet Stand      540        0.031746
14                      USB Hub      870        0.119048
15          External Hard Drive     2300        0.497354
16            Smartphone Tripod      760        0.089947
17              Laptop Backpack     1600        0.312169
18            Bluetooth Earbuds     3500        0.814815
19                LED Desk Lamp      980        0.148148
20                 Phone Holder      420        0.000000
21            Wireless Keyboard     1450        0.272487
22             Portable Monitor     1250        0.219577
23                   Smart Plug      720        0.079365
24                  WiFi Router     2100        0.444444
25              Graphics Tablet      980        0.148148
26                   VR Headset     3100        0.708995
27                   Microphone     1300        0.232804
28             Smart Light Bulb      880        0.121693
29           Laptop Cooling Pad      990        0.150794
30                Action Camera     2100        0.444444
31               Smart Doorbell     1750        0.351852
32              Streaming Stick     2500        0.550265
33           Portable Projector     1450        0.272487
34                 Gaming Chair     2100        0.444444
35               Desk Organizer      450        0.007937
36              USB Flash Drive      900        0.126984
37       Phone Screen Protector      600        0.047619
38                Laptop Sleeve      720        0.079365
39           Wireless Presenter      520        0.026455
40         Tablet Keyboard Case      850        0.113757
41             Smart Thermostat     1200        0.206349
42              Security Camera     2100        0.444444
43                 Drone Camera     1800        0.365079
44              Electric Kettle     1400        0.259259
45                    Air Fryer     2200        0.470899
46                 Robot Vacuum     1650        0.325397
47                  Smart Scale      980        0.148148
48          Digital Photo Frame      870        0.119048
49                 Portable Fan      760        0.089947

Min-Max Normalized Units Sold:
                   Product_Name  Units_Sold  Units_Sold_minmax
0                Wireless Mouse         350           0.518519
1             Bluetooth Speaker         220           0.277778
2                  USB Keyboard         180           0.203704
3                Gaming Headset         410           0.629630
4                    Smartwatch         520           0.833333
5                    Power Bank         390           0.592593
6                  Laptop Stand         140           0.129630
7                        Webcam         260           0.351852
8                  Portable SSD         330           0.481481
9              Wireless Charger         190           0.222222
10  Noise Cancelling Headphones         610           1.000000
11          Mechanical Keyboard         290           0.407407
12                 Gaming Mouse         340           0.500000
13                 Tablet Stand         120           0.092593
14                      USB Hub         200           0.240741
15          External Hard Drive         310           0.444444
16            Smartphone Tripod         210           0.259259
17              Laptop Backpack         420           0.648148
18            Bluetooth Earbuds         530           0.851852
19                LED Desk Lamp         260           0.351852
20                 Phone Holder         150           0.148148
21            Wireless Keyboard         310           0.444444
22             Portable Monitor         170           0.185185
23                   Smart Plug         210           0.259259
24                  WiFi Router         390           0.592593
25              Graphics Tablet         160           0.166667
26                   VR Headset         140           0.129630
27                   Microphone         270           0.370370
28             Smart Light Bulb         240           0.314815
29           Laptop Cooling Pad         260           0.351852
30                Action Camera         200           0.240741
31               Smart Doorbell         180           0.203704
32              Streaming Stick         430           0.666667
33           Portable Projector         120           0.092593
34                 Gaming Chair          90           0.037037
35               Desk Organizer         160           0.166667
36              USB Flash Drive         320           0.462963
37       Phone Screen Protector         380           0.574074
38                Laptop Sleeve         210           0.259259
39           Wireless Presenter         130           0.111111
40         Tablet Keyboard Case         150           0.148148
41             Smart Thermostat         110           0.074074
42              Security Camera         260           0.351852
43                 Drone Camera          70           0.000000
44              Electric Kettle         310           0.444444
45                    Air Fryer         200           0.240741
46                 Robot Vacuum         120           0.092593
47                  Smart Scale         170           0.185185
48          Digital Photo Frame         150           0.148148
49                 Portable Fan         240           0.314815

In [32]:
# 2. Z Score Normalization

df['Price_zscore'] = (df['Price'] - df['Price'].mean()) / df['Price'].std()
print("\nZ-Score Normalized Price: ")
print(df[['Product_Name','Price','Price_zscore']])

df['Rating_zscore'] = (df['Rating'] - df['Rating'].mean()) / df['Rating'].std()
print("\nZ-Score Normalized Rating: ")
print(df[['Product_Name','Rating','Rating_zscore']])

Z-Score Normalized Price:
                   Product_Name  Price  Price_zscore
0                Wireless Mouse    799     -0.692019
1             Bluetooth Speaker   1499     -0.557310
2                  USB Keyboard    699     -0.711263
3                Gaming Headset   2499     -0.364869
4                    Smartwatch   3999     -0.076207
5                    Power Bank   1199     -0.615043
6                  Laptop Stand    899     -0.672775
7                        Webcam   1899     -0.480334
8                  Portable SSD   5499      0.212455
9              Wireless Charger    999     -0.653531
10  Noise Cancelling Headphones   7999      0.693559
11          Mechanical Keyboard   4599      0.039258
12                 Gaming Mouse   1599     -0.538066
13                 Tablet Stand    699     -0.711263
14                      USB Hub    899     -0.672775
15          External Hard Drive   6499      0.404897
16            Smartphone Tripod   1199     -0.615043
17              Laptop Backpack   1999     -0.461090
18            Bluetooth Earbuds   2999     -0.268648
19                LED Desk Lamp   1299     -0.595799
20                 Phone Holder    499     -0.749752
21            Wireless Keyboard   2499     -0.364869
22             Portable Monitor   8999      0.886000
23                   Smart Plug    799     -0.692019
24                  WiFi Router   3499     -0.172428
25              Graphics Tablet   4599      0.039258
26                   VR Headset  12999      1.655766
27                   Microphone   2199     -0.422601
28             Smart Light Bulb    699     -0.711263
29           Laptop Cooling Pad   1499     -0.557310
30                Action Camera   9999      1.078442
31               Smart Doorbell   5999      0.308676
32              Streaming Stick   3499     -0.172428
33           Portable Projector  11999      1.463325
34                 Gaming Chair  15999      2.233090
35               Desk Organizer    599     -0.730508
36              USB Flash Drive    799     -0.692019
37       Phone Screen Protector    299     -0.788240
38                Laptop Sleeve    999     -0.653531
39           Wireless Presenter   1499     -0.557310
40         Tablet Keyboard Case   2999     -0.268648
41             Smart Thermostat  10999      1.270883
42              Security Camera   4999      0.116235
43                 Drone Camera  24999      3.965063
44              Electric Kettle   1999     -0.461090
45                    Air Fryer   7999      0.693559
46                 Robot Vacuum  18999      2.810415
47                  Smart Scale   2499     -0.364869
48          Digital Photo Frame   3499     -0.172428
49                 Portable Fan    999     -0.653531

Z-Score Normalized Rating:
                   Product_Name  Rating  Rating_zscore
0                Wireless Mouse     4.3      -0.421580
1             Bluetooth Speaker     4.5       0.606665
2                  USB Keyboard     4.1      -1.449825
3                Gaming Headset     4.6       1.120787
4                    Smartwatch     4.4       0.092542
5                    Power Bank     4.2      -0.935703
6                  Laptop Stand     4.0      -1.963948
7                        Webcam     4.3      -0.421580
8                  Portable SSD     4.7       1.634910
9              Wireless Charger     4.2      -0.935703
10  Noise Cancelling Headphones     4.6       1.120787
11          Mechanical Keyboard     4.5       0.606665
12                 Gaming Mouse     4.4       0.092542
13                 Tablet Stand     4.1      -1.449825
14                      USB Hub     4.2      -0.935703
15          External Hard Drive     4.6       1.120787
16            Smartphone Tripod     4.3      -0.421580
17              Laptop Backpack     4.4       0.092542
18            Bluetooth Earbuds     4.5       0.606665
19                LED Desk Lamp     4.3      -0.421580
20                 Phone Holder     4.0      -1.963948
21            Wireless Keyboard     4.4       0.092542
22             Portable Monitor     4.6       1.120787
23                   Smart Plug     4.2      -0.935703
24                  WiFi Router     4.5       0.606665
25              Graphics Tablet     4.4       0.092542
26                   VR Headset     4.7       1.634910
27                   Microphone     4.3      -0.421580
28             Smart Light Bulb     4.2      -0.935703
29           Laptop Cooling Pad     4.3      -0.421580
30                Action Camera     4.6       1.120787
31               Smart Doorbell     4.5       0.606665
32              Streaming Stick     4.4       0.092542
33           Portable Projector     4.6       1.120787
34                 Gaming Chair     4.7       1.634910
35               Desk Organizer     4.1      -1.449825
36              USB Flash Drive     4.2      -0.935703
37       Phone Screen Protector     4.0      -1.963948
38                Laptop Sleeve     4.3      -0.421580
39           Wireless Presenter     4.4       0.092542
40         Tablet Keyboard Case     4.5       0.606665
41             Smart Thermostat     4.6       1.120787
42              Security Camera     4.4       0.092542
43                 Drone Camera     4.7       1.634910
44              Electric Kettle     4.3      -0.421580
45                    Air Fryer     4.6       1.120787
46                 Robot Vacuum     4.5       0.606665
47                  Smart Scale     4.4       0.092542
48          Digital Photo Frame     4.3      -0.421580
49                 Portable Fan     4.2      -0.935703

In [35]:
# 3. Decimal Scaling - Reviews

df['Reviews_ds'] = df['Reviews'] / 10000
print("\nDecimal Scaling Normalized Reviews: ")
print(df[['Product_Name','Reviews','Reviews_ds']])

Decimal Scaling Normalized Reviews:
                   Product_Name  Reviews  Reviews_ds
0                Wireless Mouse     1520       0.152
1             Bluetooth Speaker      980       0.098
2                  USB Keyboard      870       0.087
3                Gaming Headset     2100       0.210
4                    Smartwatch     3050       0.305
5                    Power Bank     1750       0.175
6                  Laptop Stand      620       0.062
7                        Webcam     1120       0.112
8                  Portable SSD     1850       0.185
9              Wireless Charger      760       0.076
10  Noise Cancelling Headphones     4200       0.420
11          Mechanical Keyboard     2100       0.210
12                 Gaming Mouse     1300       0.130
13                 Tablet Stand      540       0.054
14                      USB Hub      870       0.087
15          External Hard Drive     2300       0.230
16            Smartphone Tripod      760       0.076
17              Laptop Backpack     1600       0.160
18            Bluetooth Earbuds     3500       0.350
19                LED Desk Lamp      980       0.098
20                 Phone Holder      420       0.042
21            Wireless Keyboard     1450       0.145
22             Portable Monitor     1250       0.125
23                   Smart Plug      720       0.072
24                  WiFi Router     2100       0.210
25              Graphics Tablet      980       0.098
26                   VR Headset     3100       0.310
27                   Microphone     1300       0.130
28             Smart Light Bulb      880       0.088
29           Laptop Cooling Pad      990       0.099
30                Action Camera     2100       0.210
31               Smart Doorbell     1750       0.175
32              Streaming Stick     2500       0.250
33           Portable Projector     1450       0.145
34                 Gaming Chair     2100       0.210
35               Desk Organizer      450       0.045
36              USB Flash Drive      900       0.090
37       Phone Screen Protector      600       0.060
38                Laptop Sleeve      720       0.072
39           Wireless Presenter      520       0.052
40         Tablet Keyboard Case      850       0.085
41             Smart Thermostat     1200       0.120
42              Security Camera     2100       0.210
43                 Drone Camera     1800       0.180
44              Electric Kettle     1400       0.140
45                    Air Fryer     2200       0.220
46                 Robot Vacuum     1650       0.165
47                  Smart Scale      980       0.098
48          Digital Photo Frame      870       0.087
49                 Portable Fan      760       0.076

In [39]:
# Turning categorical variables into quantitative variables

import pandas as pd
import numpy as np
df = pd.read_csv("/content/Student-Dataset.csv")
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [41]:
# 1. Label Encoding - Placement status

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['label_status'] = le.fit_transform(df['Placement_Status'])
df['label_status'].value_counts()

label_status
1    5
0    5
Name: count, dtype: int64

In [42]:
# 2. One-Hot Encoding - Department

df_encoded = pd.get_dummies(df, columns=['Department'])
print(df_encoded)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  label_status  Department_Civil  \
0           Placed  450000             1             False
1       Not Placed       0             0             False
2           Placed  550000             1             False
3       Not Placed       0             0             False
4           Placed  480000             1             False
5       Not Placed       0             0              True
6           Placed  500000             1             False
7       Not Placed       0             0             False
8           Placed  420000             1             False
9       Not Placed       0             0             False

   Department_Computer  Department_ENTC  Department_IT  Department_Mechanical
0                 True            False          False                  False
1                False            False           True                  False
2                False             True          False                  False
3                False            False          False                   True
4                 True            False          False                  False
5                False            False          False                  False
6                False            False           True                  False
7                 True            False          False                  False
8                False             True          False                  False
9                False            False          False                   True

In [43]:
# 3. Dummies - Department

df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)
print(df_dummy)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  label_status  Department_Computer  \
0           Placed  450000             1                 True
1       Not Placed       0             0                False
2           Placed  550000             1                False
3       Not Placed       0             0                False
4           Placed  480000             1                 True
5       Not Placed       0             0                False
6           Placed  500000             1                False
7       Not Placed       0             0                 True
8           Placed  420000             1                False
9       Not Placed       0             0                False

   Department_ENTC  Department_IT  Department_Mechanical
0            False          False                  False
1            False           True                  False
2             True          False                  False
3            False          False                   True
4            False          False                  False
5            False          False                  False
6            False           True                  False
7            False          False                  False
8             True          False                  False
9            False          False                   True